spring:
  application:
    name: "miniiam"

  datasource:
    url: jdbc:postgresql://localhost:5432/mini_iam
    username: iam_user
    password: iam_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true