version: "3.8"

services:
  db:
    image: postgres:14
    container_name: mini-iam-postgres
    restart: always
    environment:
      POSTGRES_DB: mini_iam
      POSTGRES_USER: iam_user
      POSTGRES_PASSWORD: iam_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
